config/routes.rb
Store::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match "weapons/:id" => 'frontEnds#show', :as => 'weapon', :via => :get

  resources :front_ends

  resources :weapons
  
  resources :types

  root :to => "frontEnds#index", :as => 'front_end'
  
  match "weapons/typeslist/:id" => 'frontEnds#typeslist', :as => 'type', :via => :get
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/front_end.rb
class FrontEnd < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/type.rb
class Type < ActiveRecord::Base
  attr_accessible :description, :name, :id
  
  has_many :weapons
end

app/models/weapon.rb
class Weapon < ActiveRecord::Base
  attr_accessible :created_at, :damage, :firerate, :id, :image, :magazinesize, :name, :reloadtime, :type_id
  validates :damage, :firerate, :magazinesize, :name, :reloadtime, :presence => true
  
  belongs_to :type
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/front_ends_controller.rb
class FrontEndsController < ApplicationController
  # GET /front_ends
  # GET /front_ends.json
  def index
    @front_ends = Weapon.all
    @types = Type.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @front_ends }
    end
  end
  
  def typeslist
    @type = Type.find(params[:id])
  end
  
  def show
    @weapon = Weapon.find(params[:id])
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.all
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @types }
    end
  end
  
  def show
    @type = Type.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @type }
    end
  end
  
  def new
    @type = Type.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @type }
    end
  end
  
  def edit
    @type = Type.find(params[:id])
  end
  
  def create
    @type = Type.new(params[:type])
    
    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render json: @type, status: :created, location: @type }
      else
        format.html { render action: "new" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    @type = Type.find(params[:id])
    
    respond_to do |format|
      if @type.update_attributes(params[:type])
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @type = Type.find(params[:id])
    @type.destroy
    
    respond_to do |format|
      format.html { redirect_to types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
  # GET /weapons
  # GET /weapons.json
  def index
    @weapons = Weapon.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @weapons }
    end
  end

  # GET /weapons/1
  # GET /weapons/1.json
  def show
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/new
  # GET /weapons/new.json
  def new
    @weapon = Weapon.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @weapon }
    end
  end

  # GET /weapons/1/edit
  def edit
    @weapon = Weapon.find(params[:id])
  end

  # POST /weapons
  # POST /weapons.json
  def create
    @weapon = Weapon.new(params[:weapon])

    respond_to do |format|
      if @weapon.save
        format.html { redirect_to @weapon, notice: 'Weapon was successfully created.' }
        format.json { render json: @weapon, status: :created, location: @weapon }
      else
        format.html { render action: "new" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /weapons/1
  # PUT /weapons/1.json
  def update
    @weapon = Weapon.find(params[:id])

    respond_to do |format|
      if @weapon.update_attributes(params[:weapon])
        format.html { redirect_to @weapon, notice: 'Weapon was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @weapon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /weapons/1
  # DELETE /weapons/1.json
  def destroy
    @weapon = Weapon.find(params[:id])
    @weapon.destroy

    respond_to do |format|
      format.html { redirect_to weapons_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_ends_helper.rb
module FrontEndsHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/front_ends/_form.html.erb
<%= form_for(@front_end) do |f| %>
  <% if @front_end.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front_end.errors.count, "error") %> prohibited this front_end from being saved:</h2>

      <ul>
      <% @front_end.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/front_ends/_front_end.html.erb
<div class="weaponf">  

  <h2><%= link_to weapon.name, weapon_path(weapon) %></h2>
  
  <p>
    <b>Damage:</b>
    <%= weapon.damage %>
  </p>
  <p>
    <b>Type:</b>
    <%= weapon.type.name %>
  </p>
  
  
  <% if weapon.image.present? %>
    <p>
      <%= image_tag weapon.image %>
    </p>
  <% else %>
    <p class="no_image">
      <em>No weapon image.</em>
    </p>
  <% end %>
  
</div>

app/views/front_ends/edit.html.erb
<h1>Editing front_end</h1>

<%= render 'form' %>

<%= link_to 'Show', @front_end %> |
<%= link_to 'Back', front_ends_path %>

app/views/front_ends/index.html.erb
<div id="container">
  <header>
    <h1>Welcome to the Cross Fire Black Market</h1>
    
    <h2>View Weapons by Type:</h2>
    <h3>
      <% @types.each do |t| %>
        <%= link_to t.name, type_path(t.id)%>
      <% end %>
    </h3>
  </header>
  
  <div class="content">
    <%= render :partial => 'front_end', :collection => @front_ends, :as => 'weapon' %>
  </div>
</div>

app/views/front_ends/new.html.erb
<h1>New front_end</h1>

<%= render 'form' %>

<%= link_to 'Back', front_ends_path %>

app/views/front_ends/show.html.erb
<div class="show-weapon">
  <div id="weapon-name">
    <h1><%= @weapon.name %></h1>
  </div>
  <table id="show-table">
    <tr>
      <td>Reload Time</td>
      <td>Fire Rate</td>
      <td>Magazine Size</td>
      <td>Damage</td>
      <td>Type</td>
    </tr>
    <tr>
      <td><%= @weapon.reloadtime %></td>
      <td><%= @weapon.firerate %></td>
      <td><%= @weapon.magazinesize %></td>
      <td><%= @weapon.damage %></td>
      <td><%= @weapon.type.name %></td>
    </tr>
  </table>
  
  
  <% if @weapon.image.present? %>
    <p id="show-image">
      <%= image_tag @weapon.image %>
    </p>
  <% else %>
    <p class="no_image">
      <em>No weapon image.</em>
    </p>
  <% end %>
  <footer>
    <%= link_to 'Back', front_ends_path %>
  </footer>
</div>

app/views/front_ends/typeslist.html.erb
<div id="container">
  <header>
    <h1><%= @type.name %></h1>
  </header>
  <div class="content">
    <%= render :partial => 'front_end', :collection => @type.weapons, :as => 'weapon' %>
  </div>
  <div class="clear" />
  <footer>
    <%= link_to 'Back', front_ends_path %>
  </footer>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/types/_form.html.erb
<%= form_for(@type) do |f| %>
  <% if @type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@type.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing type</h1>

<%= render 'form' %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<h1>Listing types</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @types.each do |type| %>
  <tr>
    <td><%= type.name %></td>
    <td><%= type.description %></td>
    <td><%= link_to 'Show', type %></td>
    <td><%= link_to 'Edit', edit_type_path(type) %></td>
    <td><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<footer>
  <%= link_to 'New Type', new_type_path %>
</footer>

app/views/types/new.html.erb
<h1>New type</h1>

<%= render 'form' %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @type.name %>
</p>

<p>
  <b>Description:</b>
  <%= @type.description %>
</p>


<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/weapons/_form.html.erb
<%= form_for(@weapon) do |f| %>
  <% if @weapon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
      <% @weapon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reloadtime %><br />
    <%= f.text_field :reloadtime %>
  </div>
  <div class="field">
    <%= f.label :firerate %><br />
    <%= f.text_field :firerate %>
  </div>
  <div class="field">
    <%= f.label :magazinesize %><br />
    <%= f.number_field :magazinesize %>
  </div>
  <div class="field">
    <%= f.label :damage %><br />
    <%= f.number_field :damage %>
  </div>
  <div class="field">
    <%= f.label :image %><br />
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :type_id %><br />
    <%= f.collection_select :type_id, Type.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/weapons/_weapon.html.erb
<div class="weapon">  
  <p>
  <b>Id:</b>
  <%= weapon.id %>
</p>

<p>
  <b>Name:</b>
  <%= weapon.name %>
</p>

<p>
  <b>Reloadtime:</b>
  <%= weapon.reloadtime %>
</p>

<p>
  <b>Firerate:</b>
  <%= weapon.firerate %>
</p>

<p>
  <b>Magazinesize:</b>
  <%= weapon.magazinesize %>
</p>

<p>
  <b>Damage:</b>
  <%= weapon.damage %>
</p>
<p>
  <b>Type:</b>
  <%= weapon.type.name %>
</p>


<p>
  <b>Image:</b>
  <% if weapon.image.present? %>
    <p>
      <%= image_tag weapon.image %>
    </p>
  <% else %>
    <p class="no_image">
      <em>No weapon image.</em>
    </p>
  <% end %>
</p>

<p>
  <b>Created at:</b>
  <%= weapon.created_at %>
</p>
</div>

app/views/weapons/edit.html.erb
<h1>Editing weapon</h1>

<%= render 'form' %>

<%= link_to 'Show', @weapon %> |
<%= link_to 'Back', weapons_path %>

app/views/weapons/index.html.erb
<h1>Listing weapons</h1>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Reloadtime</th>
    <th>Firerate</th>
    <th>Magazinesize</th>
    <th>Damage</th>
    <th>Type_id</th>
    <th>Image</th>
    <th>Created at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @weapons.each do |weapon| %>
  <tr>
    <td><%= weapon.id %></td>
    <td><%= weapon.name %></td>
    <td><%= weapon.reloadtime %></td>
    <td><%= weapon.firerate %></td>
    <td><%= weapon.magazinesize %></td>
    <td><%= weapon.damage %></td>
    <td><%= weapon.type_id %></td>
    <td><%= weapon.image %></td>
    <td><%= weapon.created_at %></td>
    <td><%= link_to 'Show', weapon %></td>
    <td><%= link_to 'Edit', edit_weapon_path(weapon) %></td>
    <td><%= link_to 'Destroy', weapon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Weapon', new_weapon_path %>

app/views/weapons/new.html.erb
<h1>New weapon</h1>

<%= render 'form' %>

<%= link_to 'Back', weapons_path %>

app/views/weapons/show.html.erb
<p id="notice"><%= notice %></p>

<div class="actions">
    <%= link_to 'edit', edit_weapon_path(@weapon) %>
    <%= link_to 'x', @weapon, :method => :delete, :confirm => "Are you sure you want to delete #{@weapon.name}?" %>
  </div>
<div class="weapons">
  <%= render @weapon %>
</div>


<%= link_to 'Edit', edit_weapon_path(@weapon) %> |
<%= link_to 'Back', weapons_path %>